repos:
-   repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [file, rust]
        entry: cargo fmt -- --check
        pass_filenames: false

      - id: cranky
        name: cranky
        language: system
        types: [file, rust]
        entry: cargo cranky --bins --tests --examples --all -- -D warnings
        pass_filenames: false

      - id: test
        name: test
        language: system
        types: [file, rust]
        entry: cargo nextest run
        pass_filenames: false

