[workspace]
members = [
    "add-two-numbers",
    "integer-to-roman",
    "longest-common-prefix",
    "longest-palindromic-substring",
    "longest-substring-without-repeating-characters",
    "median-of-two-sorted-arrays",
    "palindrome-number",
    "powx-n",
    "regular-expression-matching",
]
